#!/usr/bin/env node
// Stages the compiled JS, templates, and version metadata into python/vault_tasks/_bundle/
// so `python -m build` can produce a universal py3-none-any wheel.
//
// Run as: `npm run build:wheel` (which first runs `tsc`).
//
// Pure stdlib — no extra deps. Fails loudly if anything is missing.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const distDir = join(repoRoot, "dist");
const templatesDir = join(repoRoot, "templates");
const pythonPkgDir = join(repoRoot, "python", "vault_tasks");
const bundleDir = join(pythonPkgDir, "_bundle");
const packageJsonPath = join(repoRoot, "package.json");

function fail(msg) {
  console.error(`build-wheel: ${msg}`);
  process.exit(1);
}

if (!existsSync(distDir)) {
  fail(`dist/ not found at ${distDir}. Run 'tsc' first (or 'npm run build:wheel' which does).`);
}
if (!existsSync(join(distDir, "cli.js"))) {
  fail(`dist/cli.js missing — TypeScript build did not produce a CLI entry point.`);
}
if (!existsSync(templatesDir)) {
  fail(`templates/ not found at ${templatesDir}.`);
}
if (!existsSync(pythonPkgDir)) {
  fail(`python/vault_tasks/ not found at ${pythonPkgDir}. Did you check out the wheel scaffolding?`);
}

// PEP 440 version sanity. package.json uses semver — strip pre-release/build
// metadata that PEP 440 would reject in `dynamic = ["version"]` lookups.
// For now we require a clean MAJOR.MINOR.PATCH to keep wheels reproducible;
// pre-release hand-publishing can be added later if needed.
const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const version = pkg.version;
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  fail(
    `package.json version '${version}' is not a clean MAJOR.MINOR.PATCH. ` +
      `PEP 440 / hatchling expect a stable release version for wheel builds.`
  );
}

console.log(`build-wheel: staging vault-tasks ${version} into ${bundleDir}`);

// Clean previous bundle so removed files don't leak into the wheel.
rmSync(bundleDir, { recursive: true, force: true });
mkdirSync(bundleDir, { recursive: true });

// Copy compiled JS, but skip tests — the wheel only needs runtime artifacts.
cpSync(distDir, join(bundleDir, "dist"), {
  recursive: true,
  filter: (src) => !src.includes(`${distDir}/tests`) && !src.endsWith(".tsbuildinfo"),
});

cpSync(templatesDir, join(bundleDir, "templates"), { recursive: true });

const versionPyPath = join(pythonPkgDir, "_version.py");
writeFileSync(
  versionPyPath,
  `# Generated by scripts/build-wheel.mjs from package.json. Do not edit.\n` +
    `__version__ = "${version}"\n`
);

console.log(`build-wheel: wrote ${versionPyPath}`);
console.log(`build-wheel: bundle ready. Next: 'cd python && python -m build'`);
