#!/usr/bin/env node
// Stages the compiled JS, templates, and version metadata into python/vault_tasks/_bundle/
// so `python -m build` can produce a universal py3-none-any wheel.
//
// Run as: `npm run build:wheel` (which first runs `tsc`).
//
// Pure stdlib — no extra deps. Fails loudly if anything is missing.

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const distDir = join(repoRoot, "dist");
const templatesDir = join(repoRoot, "templates");
const pythonDir = join(repoRoot, "python");
const pythonPkgDir = join(pythonDir, "vault_tasks");
const bundleDir = join(pythonPkgDir, "_bundle");
const packageJsonPath = join(repoRoot, "package.json");
const rootReadmePath = join(repoRoot, "README.md");
const pythonReadmePath = join(pythonDir, "README.md");

function fail(msg) {
  console.error(`build-wheel: ${msg}`);
  process.exit(1);
}

if (!existsSync(distDir)) {
  fail(`dist/ not found at ${distDir}. Run 'tsc' first (or 'npm run build:wheel' which does).`);
}
if (!existsSync(join(distDir, "cli.js"))) {
  fail(`dist/cli.js missing — TypeScript build did not produce a CLI entry point.`);
}
if (!existsSync(templatesDir)) {
  fail(`templates/ not found at ${templatesDir}.`);
}
if (!existsSync(pythonPkgDir)) {
  fail(`python/vault_tasks/ not found at ${pythonPkgDir}. Did you check out the wheel scaffolding?`);
}

// Version source: VAULT_TASKS_VERSION_OVERRIDE env var (used by the TestPyPI
// dispatch workflow to mint unique dev versions like `0.3.0.dev17`) takes
// precedence over package.json. For real releases the override is unset and
// version comes from package.json — npm and PyPI ship in lockstep.
const pkg = JSON.parse(readFileSync(packageJsonPath, "utf-8"));
const versionOverride = process.env.VAULT_TASKS_VERSION_OVERRIDE;
const version = versionOverride || pkg.version;
// Accept clean releases (1.2.3) or PEP 440 pre/dev/post variants used by the
// TestPyPI dry-run path. Reject anything else early so a bad override does
// not produce an unpublishable wheel.
const versionPattern = /^\d+\.\d+\.\d+(?:(?:a|b|rc)\d+|\.dev\d+|\.post\d+)?$/;
if (!versionPattern.test(version)) {
  fail(
    `version '${version}' is not a valid PEP 440 release. ` +
      `Expected MAJOR.MINOR.PATCH or MAJOR.MINOR.PATCH.{devN|postN|aN|bN|rcN}.` +
      (versionOverride ? ` (from VAULT_TASKS_VERSION_OVERRIDE)` : ` (from package.json)`)
  );
}

console.log(`build-wheel: staging vault-tasks ${version} into ${bundleDir}`);

// Clean previous bundle so removed files don't leak into the wheel.
rmSync(bundleDir, { recursive: true, force: true });
mkdirSync(bundleDir, { recursive: true });

// Copy compiled JS, but skip tests — the wheel only needs runtime artifacts.
// Use path.relative + path.sep so the test-directory filter works on Windows
// (where cpSync hands callbacks paths with `\\` separators) as well as POSIX.
cpSync(distDir, join(bundleDir, "dist"), {
  recursive: true,
  filter: (src) => {
    if (src.endsWith(".tsbuildinfo")) return false;
    const rel = relative(distDir, src);
    return rel !== "tests" && !rel.startsWith(`tests${sep}`);
  },
});

cpSync(templatesDir, join(bundleDir, "templates"), { recursive: true });

const versionPyPath = join(pythonPkgDir, "_version.py");
writeFileSync(
  versionPyPath,
  `# Generated by scripts/build-wheel.mjs from package.json. Do not edit.\n` +
    `__version__ = "${version}"\n`
);

console.log(`build-wheel: wrote ${versionPyPath}`);

// Mirror the repo-root README into python/README.md so the PyPI project page
// shows the full command reference. python/README.md is gitignored; running
// `python -m build` directly without first running this script will fail
// fast with hatchling's "README.md not found" rather than shipping a stub.
if (!existsSync(rootReadmePath)) {
  fail(`README.md not found at ${rootReadmePath}.`);
}
const rootReadme = readFileSync(rootReadmePath, "utf-8");
writeFileSync(pythonReadmePath, rootReadme);
console.log(`build-wheel: wrote ${pythonReadmePath} from repo-root README`);

console.log(`build-wheel: bundle ready. Next: 'cd python && python -m build'`);
